spring:
    datasource:
      url: jdbc:mysql://localhost:3306/webclassdesign_team?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: root
      password: 312127
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8181